# Generated by Django 6.0.5 on 2026-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('fecha_publicacion', models.DateField()),
                ('categorias', models.ManyToManyField(related_name='categorias', to='categorias.categoria')),
            ],
        ),
    ]
